title: Introduction to Python and Microcontrollers
description: A hands on course using the Freenove Ultimate Starter kit for ESP32-S3 model FNK0082 to teach basic Python, Microcontroller and electronics concepts.
theme: jekyll-theme-minimal

navigation:
  - title: Getting Started
    link: /setup/getting_started.html
  - title: Module 1 - First Examples
    link: /01_first_examples/index.html
    sublist:
      - title: Blink (Built-in LED)
        link: /01_first_examples/01_01_blink.html
      - title: Blink (External LED)
        link: /01_first_examples/01_02_blink_external_led.html
      - title: Button and LED
        link: /01_first_examples/01_03_button_and_led.html
      - title: Button and LED On/Off Switch
        link: /01_first_examples/01_03a_button_and_led_on_off.html
      - title: Breathing LED
        link: /01_first_examples/01_04_breathing_led.html
  - title: Module 2 - Input and Output
    link: /02_input_output/index.html
    sublist:
      - title: Flowing Light
        link: /02_input_output/02_01_flowing_light.html
      - title: Flowing Light with PWM
        link: /02_input_output/02_02_flowing_light_with_pwm.html
      - title: Gradient Color Light
        link: /02_input_output/02_03_gradient_color_light.html
      - title: LED Pixel
        link: /02_input_output/02_04_led_pixel.html
      - title: Rainbow Light
        link: /02_input_output/02_05_rainbow_light.html
      - title: Read the Voltage of a Potentiometer
        link: /02_input_output/02_06_read_voltage_potentiometer.html
      - title: Soft Light
        link: /02_input_output/02_07_soft_light.html
  - title: Module 3 - Sensors
    link: /03_sensors/index.html
    sublist:
      - title: Night Lamp
        link: /03_sensors/03_01_night_lamp.html
      - title: Thermometer
        link: /03_sensors/03_02_thermometer.html
      - title: Joystick
        link: /03_sensors/03_03_joystick.html
      - title: Ultrasonic Ranging
        link: /03_sensors/03_04_ultrasonic_ranging.html
      - title: Ultrasonic Ranging (with the hcsr04 module)
        link: /03_sensors/03_05_ultrasonic_ranging_2.html
      - title: Hygrothermograph (DHT11)
        link: /03_sensors/03_06_hygrothermograph_dht11.html
      - title: Matrix Keypad
        link: /03_sensors/03_07_matrix_keypad.html
      - title: MPU6050 Attitude Sensor
        link: /03_sensors/03_08_mpu6050_attitude_sensor.html
  - title: Module 4 - Output
    link: /04_output/index.html
    sublist:
      - title: 7-Segment Display
        link: /04_output/04_01_seven_segment_display.html
      - title: Four Digit Seven Segment Display
        link: /04_output/04_02_four_digit_seven_segment.html
      - title: LCD1602 Display
        link: /04_output/04_03_lcd1602.html
      - title: Motor & Driver - Control Motor with Potentiometer
        link: /04_output/04_04_motor_driver.html
      - title: Servo Sweep
        link: /04_output/04_05_servo_sweep.html
      - title: Servo Knob
        link: /04_output/04_06_servo_knob.html
      - title: Stepper Motor
        link: /04_output/04_07_stepper_motor.html
      - title: Hygrothermograph (DHT11 + LCD1602)
        link: /04_output/04_08_hygrothermograph_dht11_2.html
  - title: Module 5 - Advanced
    link: /05_advanced/index.html
    sublist:
      - title: Interrupts
        link: /05_advanced/05_01_interrupts.html