title: Introduction to Python and Microcontrollers
description: A hands on course using the Freenove Ultimate Starter kit for ESP32-S3 model FNK0082 to teach basic Python, Microcontroller and electronics concepts.
theme: jekyll-theme-minimal
